#!/usr/bin/env bash

# gcloud multiplexing for shared GCE/GKE tests.
GRS_ROOT=$(dirname "${BASH_SOURCE[0]}")

SIM_NUM=${SIM_NUM:-2}
CLIENT_NUM=${CLIENT_NUM:-4}
SERVER_NUM=${SERVER_NUM:-1}
ZONE=${GRS_GCE_ZONE:-"us-central1-a"}
REGION=${ZONE%-*}
PROJECT=${GRS_GCE_project:-"workload-controller-manager"}
INSTANCE_PREFIX=${GRS_INSTANCE_PREFIX:-grs}
SIM_INSTANCE_PREFIX=${SIM_INSTANCE_PREFIX:-"${INSTANCE_PREFIX}-sim"}
CLIENT_INSTANCE_PREFIX=${CLIENT_INSTANCE_PREFIX:-"${INSTANCE_PREFIX}-client"}
SERVER_INSTANCE_PREFIX=${SERVER_INSTANCE_PREFIX:-"${INSTANCE_PREFIX}-server"}

SOURCE_INSTANCE=${SOURCE_INSTANCE:-"sonya-grs-test-template"}
SOURCE_DISK=${SOURCE_DISK:-"sonya-grs-test-template"}
SOURCE_DISK_ZONE=${SOURCE_DISK_ZONE:-"${ZONE}"}
IMAGE_NAME=${IMAGE_NAME:-"grs-test-image"}

# simulator instance parameter
SIM_SOURCE_INSTANCE=${SIM_SOURCE_INSTANCE:-"${SOURCE_INSTANCE}"}
SIM_SOURCE_DISK=${SIM_SOURCE_DISK:-"${SOURCE_DISK}"}
SIM_SOURCE_DISK_ZONE=${SIM_SOURCE_DISK_ZONE:-"${SOURCE_DISK_ZONE}"}
SIM_IMAGE_NAME=${SIM_IMAGE_NAME:-"${IMAGE_NAME}"}
SIM_ZONE=${SIM_ZONE:-"${SIM_SOURCE_DISK_ZONE}"}


# client instance parameter
CLIENT_SOURCE_INSTANCE=${CLIENT_SOURCE_INSTANCE:-"${SOURCE_INSTANCE}"}
CLIENT_SOURCE_DISK=${CLIENT_SOURCE_DISK:-"${SOURCE_DISK}"}
CLIENT_SOURCE_DISK_ZONE=${CLIENT_SOURCE_DISK_ZONE:-"${SOURCE_DISK_ZONE}"}
CLIENT_IMAGE_NAME=${CLIENT_IMAGE_NAME:-"${IMAGE_NAME}"}
CLIENT_ZONE=${CLIENT_ZONE:-"${CLIENT_SOURCE_DISK_ZONE}"}

# server instance parameter
SERVER_SOURCE_INSTANCE=${SERVER_SOURCE_INSTANCE:-"sonya-grs-resourcemanagement"}
SERVER_SOURCE_DISK=${SERVER_SOURCE_DISK:-"sonya-grs-resourcemanagement"}
SERVER_SOURCE_DISK_ZONE=${SERVER_SOURCE_DISK_ZONE:-"${ZONE}"}
SERVER_IMAGE_NAME=${SERVER_IMAGE_NAME:-"grs-server-image"}
SERVER_ZONE=${SERVER_ZONE:-"${SERVER_SOURCE_DISK_ZONE}"}

#teardown parameter
SERVER_AUTO_DELETE=${SERVER_AUTO_DELETE:-true}
CLIENT_AUTO_DELETE=${CLIENT_AUTO_DELETE:-true}
SIM_AUTO_DELETE=${SIM_AUTO_DELETE:-true}
SERVERIMAGE_AUTO_DELETE=${SERVERIMAGE_AUTO_DELETE:-false}
CLIENTIMAGE_AUTO_DELETE=${CLIENTIMAGE_AUTO_DELETE:-false}
SIMIMAGE_AUTO_DELETE=${SIMIMAGE_AUTO_DELETE:-false}